const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.TiledBg,
		C3.Behaviors.solid,
		C3.Plugins.Sprite,
		C3.Behaviors.Platform,
		C3.Behaviors.scrollto,
		C3.Behaviors.Persist,
		C3.Plugins.Keyboard,
		C3.Behaviors.Flash,
		C3.Behaviors.Bullet,
		C3.Behaviors.destroy,
		C3.Behaviors.Rotate,
		C3.Plugins.Spritefont2,
		C3.Plugins.Audio,
		C3.Plugins.Button,
		C3.Plugins.Mouse,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Keyboard.Cnds.OnKeyReleased,
		C3.Behaviors.Platform.Cnds.IsMoving,
		C3.Behaviors.Platform.Cnds.OnStop,
		C3.Behaviors.Platform.Cnds.IsJumping,
		C3.Behaviors.Platform.Cnds.OnLand,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Behaviors.solid.Acts.SetEnabled,
		C3.Behaviors.Platform.Acts.SetEnabled,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Spritefont2.Acts.SetVisible,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Sprite.Acts.InstanceWaitForSignal,
		C3.Plugins.Mouse.Cnds.OnObjectClicked
	];
};
self.C3_JsPropNameTable = [
	{PlanoDeFundoEmBlocos: 0},
	{Sólido: 0},
	{Chão: 0},
	{Chave: 0},
	{Bomba: 0},
	{Plataforma: 0},
	{CentrarEm: 0},
	{Persistir: 0},
	{Jogador: 0},
	{Teclado: 0},
	{Direcao: 0},
	{Piscar: 0},
	{Inimigo: 0},
	{Sprite4: 0},
	{Sprite5: 0},
	{Sprite6: 0},
	{Sprite7: 0},
	{Sprite8: 0},
	{Sprite9: 0},
	{Senso1: 0},
	{Senso2: 0},
	{Baú: 0},
	{Suporte: 0},
	{Sensor: 0},
	{InimigoCanhão: 0},
	{Canhão: 0},
	{Projétil: 0},
	{DestruirForaDoLayout: 0},
	{Girar: 0},
	{Bala: 0},
	{VidasHUD: 0},
	{ChaveHUD: 0},
	{Black: 0},
	{JogadorDialogo: 0},
	{FonteDeSprites: 0},
	{Áudio: 0},
	{Porta: 0},
	{Chefão: 0},
	{BombaSpawn: 0},
	{Menu: 0},
	{btn_Start: 0},
	{Mouse: 0},
	{start: 0},
	{Sprite: 0},
	{Sprite2: 0},
	{Vidas: 0},
	{hasBomba: 0},
	{Vidas2: 0},
	{hasBomba2: 0}
];

self.InstanceType = {
	PlanoDeFundoEmBlocos: class extends self.ITiledBackgroundInstance {},
	Chão: class extends self.ITiledBackgroundInstance {},
	Jogador: class extends self.ISpriteInstance {},
	Teclado: class extends self.IInstance {},
	Inimigo: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	Senso1: class extends self.ISpriteInstance {},
	Senso2: class extends self.ISpriteInstance {},
	Baú: class extends self.ISpriteInstance {},
	Suporte: class extends self.ISpriteInstance {},
	Sensor: class extends self.ISpriteInstance {},
	InimigoCanhão: class extends self.ISpriteInstance {},
	Canhão: class extends self.ISpriteInstance {},
	Bala: class extends self.ISpriteInstance {},
	VidasHUD: class extends self.ISpriteInstance {},
	ChaveHUD: class extends self.ISpriteInstance {},
	Chave: class extends self.ISpriteInstance {},
	Black: class extends self.ISpriteInstance {},
	JogadorDialogo: class extends self.ISpriteInstance {},
	FonteDeSprites: class extends self.ISpriteFontInstance {},
	Bomba: class extends self.ISpriteInstance {},
	Áudio: class extends self.IInstance {},
	Porta: class extends self.ISpriteInstance {},
	Chefão: class extends self.ISpriteInstance {},
	BombaSpawn: class extends self.ISpriteInstance {},
	Menu: class extends self.ISpriteInstance {},
	btn_Start: class extends self.IButtonInstance {},
	Mouse: class extends self.IInstance {},
	start: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {}
}